/**
 * Version information for guess-the-verb-sharpee
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '2.0.0';
export const BUILD_DATE = '2026-09-17T06:56:58Z';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE } as const;
